#!/usr/bin/env node
import { build } from 'esbuild'
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const BRIDGE_DIR = dirname(fileURLToPath(import.meta.url))
const ROOT = dirname(BRIDGE_DIR)
const PLUGIN = join(ROOT, 'plugins', 'intercom')

mkdirSync(join(PLUGIN, 'dist'), { recursive: true })
await build({
  entryPoints: [join(BRIDGE_DIR, 'bridge.mjs')],
  outfile: join(PLUGIN, 'dist', 'bridge.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: false,
  legalComments: 'eof',
  banner: { js: '// Generated by bridge/build-plugin.mjs; do not edit directly.' },
})
const bundlePath = join(PLUGIN, 'dist', 'bridge.mjs')
writeFileSync(bundlePath, readFileSync(bundlePath, 'utf8').replace(/[ \t]+$/gm, ''))

for (const relative of [
  'codex/launch.mjs',
  'codex/relay.mjs',
  'codex/app-server-client.mjs',
  'bridge/chat-db.mjs',
]) {
  const target = join(PLUGIN, 'runtime', relative)
  mkdirSync(dirname(target), { recursive: true })
  copyFileSync(resolve(ROOT, relative), target)
}

process.stdout.write(`Built Intercom plugin runtime at ${PLUGIN}\n`)
